In [1]:
from numpy import *
import scipy.linalg

In [2]:
a = array([[1,2,3], [4,5,6]])

In [3]:
a.ndim

2

In [4]:
a.size

6

In [5]:
a.shape

(2, 3)

In [6]:
a.shape[2-1]

3

In [7]:
array([[1.,2.,3.], [4.,5.,6.]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
a = array([[1,1,1], [1,1,1]])
b = array([[2,2], [2,2]])
c = array([3,3,3])
d = array([4,4])
block([[a,b], [c,d]])

array([[1, 1, 1, 2, 2],
       [1, 1, 1, 2, 2],
       [3, 3, 3, 4, 4]])

In [9]:
a = array([1,2,3])
a[-1]

3

In [10]:
a = array([[1.,2.,3.,4.,5.], [4.,5.,6.,7.,8.]])
a[1,4]

8.0

In [11]:
a[1]

array([4., 5., 6., 7., 8.])

In [12]:
a = random.rand(10,5)
print(f'a:\n{a}')
print(f'a[:5]:\n{a[:5]}')
print(f'a[:5]:\n{a[-5:]}')

a:
[[0.01729531 0.57649894 0.09180861 0.88016508 0.87318198]
 [0.58984654 0.57285175 0.53901248 0.26265114 0.70547284]
 [0.00602615 0.12528234 0.12100624 0.91153042 0.09623694]
 [0.6258669  0.95592713 0.39914641 0.35721493 0.64905853]
 [0.899791   0.45729886 0.61432762 0.65562973 0.60756344]
 [0.687626   0.41314099 0.29696162 0.04361637 0.81324007]
 [0.05798282 0.67492382 0.85158699 0.27351598 0.64103302]
 [0.085656   0.37490804 0.48706402 0.74075239 0.27497105]
 [0.09025748 0.19831444 0.48786804 0.11024733 0.74356721]
 [0.36159903 0.86571177 0.24873066 0.21741814 0.18218224]]
a[:5]:
[[0.01729531 0.57649894 0.09180861 0.88016508 0.87318198]
 [0.58984654 0.57285175 0.53901248 0.26265114 0.70547284]
 [0.00602615 0.12528234 0.12100624 0.91153042 0.09623694]
 [0.6258669  0.95592713 0.39914641 0.35721493 0.64905853]
 [0.899791   0.45729886 0.61432762 0.65562973 0.60756344]]
a[:5]:
[[0.687626   0.41314099 0.29696162 0.04361637 0.81324007]
 [0.05798282 0.67492382 0.85158699 0.27351598 0.64103

In [13]:
a[0:3][:,4:9]

array([[0.87318198],
       [0.70547284],
       [0.09623694]])

In [14]:
a[ix_([1,3,4],[0,2])]

array([[0.58984654, 0.53901248],
       [0.6258669 , 0.39914641],
       [0.899791  , 0.61432762]])

In [15]:
a[0:5:2,:]

array([[0.01729531, 0.57649894, 0.09180861, 0.88016508, 0.87318198],
       [0.00602615, 0.12528234, 0.12100624, 0.91153042, 0.09623694],
       [0.899791  , 0.45729886, 0.61432762, 0.65562973, 0.60756344]])

In [16]:
a[ ::2,:]

array([[0.01729531, 0.57649894, 0.09180861, 0.88016508, 0.87318198],
       [0.00602615, 0.12528234, 0.12100624, 0.91153042, 0.09623694],
       [0.899791  , 0.45729886, 0.61432762, 0.65562973, 0.60756344],
       [0.05798282, 0.67492382, 0.85158699, 0.27351598, 0.64103302],
       [0.09025748, 0.19831444, 0.48786804, 0.11024733, 0.74356721]])

In [17]:
a[ ::-1,:]

array([[0.36159903, 0.86571177, 0.24873066, 0.21741814, 0.18218224],
       [0.09025748, 0.19831444, 0.48786804, 0.11024733, 0.74356721],
       [0.085656  , 0.37490804, 0.48706402, 0.74075239, 0.27497105],
       [0.05798282, 0.67492382, 0.85158699, 0.27351598, 0.64103302],
       [0.687626  , 0.41314099, 0.29696162, 0.04361637, 0.81324007],
       [0.899791  , 0.45729886, 0.61432762, 0.65562973, 0.60756344],
       [0.6258669 , 0.95592713, 0.39914641, 0.35721493, 0.64905853],
       [0.00602615, 0.12528234, 0.12100624, 0.91153042, 0.09623694],
       [0.58984654, 0.57285175, 0.53901248, 0.26265114, 0.70547284],
       [0.01729531, 0.57649894, 0.09180861, 0.88016508, 0.87318198]])

In [18]:
a[r_[:len(a),0]]

array([[0.01729531, 0.57649894, 0.09180861, 0.88016508, 0.87318198],
       [0.58984654, 0.57285175, 0.53901248, 0.26265114, 0.70547284],
       [0.00602615, 0.12528234, 0.12100624, 0.91153042, 0.09623694],
       [0.6258669 , 0.95592713, 0.39914641, 0.35721493, 0.64905853],
       [0.899791  , 0.45729886, 0.61432762, 0.65562973, 0.60756344],
       [0.687626  , 0.41314099, 0.29696162, 0.04361637, 0.81324007],
       [0.05798282, 0.67492382, 0.85158699, 0.27351598, 0.64103302],
       [0.085656  , 0.37490804, 0.48706402, 0.74075239, 0.27497105],
       [0.09025748, 0.19831444, 0.48786804, 0.11024733, 0.74356721],
       [0.36159903, 0.86571177, 0.24873066, 0.21741814, 0.18218224],
       [0.01729531, 0.57649894, 0.09180861, 0.88016508, 0.87318198]])

In [19]:
a.T

array([[0.01729531, 0.58984654, 0.00602615, 0.6258669 , 0.899791  ,
        0.687626  , 0.05798282, 0.085656  , 0.09025748, 0.36159903],
       [0.57649894, 0.57285175, 0.12528234, 0.95592713, 0.45729886,
        0.41314099, 0.67492382, 0.37490804, 0.19831444, 0.86571177],
       [0.09180861, 0.53901248, 0.12100624, 0.39914641, 0.61432762,
        0.29696162, 0.85158699, 0.48706402, 0.48786804, 0.24873066],
       [0.88016508, 0.26265114, 0.91153042, 0.35721493, 0.65562973,
        0.04361637, 0.27351598, 0.74075239, 0.11024733, 0.21741814],
       [0.87318198, 0.70547284, 0.09623694, 0.64905853, 0.60756344,
        0.81324007, 0.64103302, 0.27497105, 0.74356721, 0.18218224]])

In [20]:
a.conj().T

array([[0.01729531, 0.58984654, 0.00602615, 0.6258669 , 0.899791  ,
        0.687626  , 0.05798282, 0.085656  , 0.09025748, 0.36159903],
       [0.57649894, 0.57285175, 0.12528234, 0.95592713, 0.45729886,
        0.41314099, 0.67492382, 0.37490804, 0.19831444, 0.86571177],
       [0.09180861, 0.53901248, 0.12100624, 0.39914641, 0.61432762,
        0.29696162, 0.85158699, 0.48706402, 0.48786804, 0.24873066],
       [0.88016508, 0.26265114, 0.91153042, 0.35721493, 0.65562973,
        0.04361637, 0.27351598, 0.74075239, 0.11024733, 0.21741814],
       [0.87318198, 0.70547284, 0.09623694, 0.64905853, 0.60756344,
        0.81324007, 0.64103302, 0.27497105, 0.74356721, 0.18218224]])

In [21]:
a = array([[1,2],[3,4]])
b = array([[2,2],[2,2]])
a @ b

array([[ 6,  6],
       [14, 14]])

In [22]:
a * b

array([[2, 4],
       [6, 8]])

In [23]:
a / b

array([[0.5, 1. ],
       [1.5, 2. ]])

In [24]:
a**3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [25]:
(a>2)

array([[False, False],
       [ True,  True]])

In [26]:
nonzero(a>2)

(array([1, 1], dtype=int64), array([0, 1], dtype=int64))

In [27]:
a[:,nonzero(a>2)[0]]

array([[2, 2],
       [4, 4]])

In [28]:
a[a<0.5]=0

In [30]:
a * (a>2)

array([[0, 0],
       [3, 4]])

In [32]:
a[:] = 3
a

array([[3, 3],
       [3, 3]])

In [34]:
y = a.copy()
y

array([[3, 3],
       [3, 3]])

In [36]:
y = a[1,:].copy()
y

array([3, 3])

In [38]:
a.flatten()

array([3, 3, 3, 3])

In [39]:
arange(1.,11.)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
arange(1.,11.)[:, newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [42]:
zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [44]:
ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
diag(a)

array([3, 3])

In [47]:
diag(a,0)

array([3, 3])

In [48]:
random.rand(3,4)

array([[0.82169063, 0.21455131, 0.28708338, 0.71345646],
       [0.93622609, 0.30865049, 0.66984879, 0.1198832 ],
       [0.78675982, 0.64101338, 0.50644159, 0.62456952]])

In [49]:
linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [50]:
mgrid[0:9.,0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [51]:
ogrid[0:9.,0:6.]

[array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]), array([[0., 1., 2., 3., 4., 5.]])]

In [52]:
meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]), array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [53]:
tile(a, (2, 3))

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [54]:
a.max()

3

In [55]:
a.max(0)

array([3, 3])

In [56]:
a.max(1)

array([3, 3])

In [57]:
sqrt(a @ a)

array([[4.24264069, 4.24264069],
       [4.24264069, 4.24264069]])

In [58]:
b = eye(2,2)
logical_and(a,b)

array([[ True, False],
       [False,  True]])

In [59]:
logical_or(a,b)

array([[ True,  True],
       [ True,  True]])

In [64]:
a = array([[1,2],[3,4]])
linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [65]:
linalg.pinv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [66]:
linalg.matrix_rank(a)

2

In [67]:
b = array([1,2])
linalg.solve(a,b)

array([0. , 0.5])

In [71]:
a = random.rand(2,2)
linalg.cholesky(a).T

array([[0.95573367, 0.36456928],
       [0.        , 0.24633542]])

In [72]:
D,V = linalg.eig(a)